"""Initial migration w/ updated schema

Revision ID: 1c8dd5e991a6
Revises: 
Create Date: 2024-08-08 14:50:45.777221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8dd5e991a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('recipe_image', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=250), nullable=True),
    sa.Column('author', sa.JSON(), nullable=True),
    sa.Column('c_notes', sa.Text(), nullable=True),
    sa.Column('prep_time', sa.String(length=50), nullable=False),
    sa.Column('cook_time', sa.String(length=50), nullable=False),
    sa.Column('total_time', sa.String(length=50), nullable=True),
    sa.Column('recipe_yield', sa.Integer(), nullable=False),
    sa.Column('recipe_cuisine', sa.JSON(), nullable=True),
    sa.Column('suitable_for_diet', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('recipe_ingredients', sa.JSON(), nullable=False),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ingredients_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('c_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='fk_ingredients_section_recipe'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruction_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('c_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='fk_instruction_section_recipe'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['ingredients_master.name'], name='fk_ingredients_master'),
    sa.ForeignKeyConstraint(['section_id'], ['ingredients_section.id'], name='fk_ingredients_section'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruction_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('c_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['instruction_section.id'], name='fk_instruction_step_section'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruction_step')
    op.drop_table('ingredients')
    op.drop_table('instruction_section')
    op.drop_table('ingredients_section')
    op.drop_table('user')
    op.drop_table('recipe')
    op.drop_table('ingredients_master')
    # ### end Alembic commands ###
