"""Add raw ingredient and instruction capture to recipe

Revision ID: 32019634ca32
Revises: 1c8dd5e991a6
Create Date: 2024-08-08 15:16:15.180751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '32019634ca32'
down_revision = '1c8dd5e991a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_ingredients_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recipe_ingredients_raw', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recipe_instructions_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recipe_instructions_raw', sa.Text(), nullable=True))
        batch_op.drop_column('recipe_ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_ingredients', sqlite.JSON(), nullable=False))
        batch_op.drop_column('recipe_instructions_raw')
        batch_op.drop_column('recipe_instructions_json')
        batch_op.drop_column('recipe_ingredients_raw')
        batch_op.drop_column('recipe_ingredients_json')

    # ### end Alembic commands ###
